# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2024_JPMC_Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2024_JPMC_Weather

  target '2024_JPMC_WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
